/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DesignsProjectIdRouteImport } from './routes/designs.$projectId'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminProjectIdRouteImport } from './routes/admin.$projectId'
import { Route as AdminDesignsProjectIdRouteImport } from './routes/admin.designs.$projectId'
import { Route as AdminChecklistProjectIdRouteImport } from './routes/admin.checklist.$projectId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsProjectIdRoute = DesignsProjectIdRouteImport.update({
  id: '/designs/$projectId',
  path: '/designs/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectIdRoute = AdminProjectIdRouteImport.update({
  id: '/admin/$projectId',
  path: '/admin/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignsProjectIdRoute = AdminDesignsProjectIdRouteImport.update({
  id: '/admin/designs/$projectId',
  path: '/admin/designs/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChecklistProjectIdRoute = AdminChecklistProjectIdRouteImport.update({
  id: '/admin/checklist/$projectId',
  path: '/admin/checklist/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$projectId': typeof AdminProjectIdRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/designs/$projectId': typeof DesignsProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/checklist/$projectId': typeof AdminChecklistProjectIdRoute
  '/admin/designs/$projectId': typeof AdminDesignsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$projectId': typeof AdminProjectIdRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/designs/$projectId': typeof DesignsProjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/checklist/$projectId': typeof AdminChecklistProjectIdRoute
  '/admin/designs/$projectId': typeof AdminDesignsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$projectId': typeof AdminProjectIdRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/designs/$projectId': typeof DesignsProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/checklist/$projectId': typeof AdminChecklistProjectIdRoute
  '/admin/designs/$projectId': typeof AdminDesignsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/$projectId'
    | '/admin/catalog'
    | '/admin/customers'
    | '/designs/$projectId'
    | '/admin/'
    | '/admin/checklist/$projectId'
    | '/admin/designs/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/$projectId'
    | '/admin/catalog'
    | '/admin/customers'
    | '/designs/$projectId'
    | '/admin'
    | '/admin/checklist/$projectId'
    | '/admin/designs/$projectId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/$projectId'
    | '/admin/catalog'
    | '/admin/customers'
    | '/designs/$projectId'
    | '/admin/'
    | '/admin/checklist/$projectId'
    | '/admin/designs/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminProjectIdRoute: typeof AdminProjectIdRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  DesignsProjectIdRoute: typeof DesignsProjectIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChecklistProjectIdRoute: typeof AdminChecklistProjectIdRoute
  AdminDesignsProjectIdRoute: typeof AdminDesignsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/$projectId': {
      id: '/designs/$projectId'
      path: '/designs/$projectId'
      fullPath: '/designs/$projectId'
      preLoaderRoute: typeof DesignsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$projectId': {
      id: '/admin/$projectId'
      path: '/admin/$projectId'
      fullPath: '/admin/$projectId'
      preLoaderRoute: typeof AdminProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/designs/$projectId': {
      id: '/admin/designs/$projectId'
      path: '/admin/designs/$projectId'
      fullPath: '/admin/designs/$projectId'
      preLoaderRoute: typeof AdminDesignsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checklist/$projectId': {
      id: '/admin/checklist/$projectId'
      path: '/admin/checklist/$projectId'
      fullPath: '/admin/checklist/$projectId'
      preLoaderRoute: typeof AdminChecklistProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminProjectIdRoute: AdminProjectIdRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  DesignsProjectIdRoute: DesignsProjectIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminChecklistProjectIdRoute: AdminChecklistProjectIdRoute,
  AdminDesignsProjectIdRoute: AdminDesignsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
